# Generated by Django 3.1.1 on 2020-09-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='geenre',
        #     old_name='title',
        #     new_name='geenre',
        # ),
        # migrations.AddField(
        #     model_name='film',
        #     name='cover',
        #     field=models.FileField(default='tet', upload_to=''),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='film',
        #     name='status',
        #     field=models.CharField(choices=[('Coming Soon', 'Coming Soon'), ('Now', 'Now')], default='tet', max_length=20),
        #     preserve_default=False,
        # ),
    ]
