# Generated by Django 3.1.1 on 2020-09-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20200915_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geenre',
            old_name='geenre',
            new_name='geenre_title',
        ),
    ]
