# Generated by Django 3.1.1 on 2020-09-15 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20200915_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teather',
            old_name='title',
            new_name='room',
        ),
    ]
